"use client";
import { useState } from "react";
import { excavatorTypes, truckTypes, normKey, type Settings } from "@/lib/production-domain";
import { TimeFields } from "./ProductionTable";
import { saveProductionSettings, settingsAudit } from "./actions";

export function ProductionSettings({ initial, onSaved, onBack }: { initial: Settings; onSaved: (settings: Settings) => void; onBack: () => void }) {
  const [settings, setSettings] = useState<Settings>(structuredClone(initial));
  const [pending, setPending] = useState(false), [message, setMessage] = useState("");
  const [issues, setIssues] = useState<Array<{ path: string; message: string }>>([]);
  const [audit, setAudit] = useState<Array<{ id: string; author: string; at: string }>>([]);
  const [dirty, setDirty] = useState(false);
  const change = (next: Settings) => { setSettings(next); setDirty(true); setMessage(""); };
  async function save() {
    setPending(true); setMessage("");
    try { const result = await saveProductionSettings(settings); if (result.ok) { setSettings(result.value); setDirty(false); setIssues([]); onSaved(result.value); setMessage("Настройки сохранены. Новые значения применятся к новым периодам и после сброса текущей формы. История сохранена."); } else { setMessage(result.message); setIssues(result.issues); } }
    catch { setMessage("Не удалось связаться с сервером. Настройки остаются на экране"); } finally { setPending(false); }
  }
  return <section className="sp-settings"><div className="sp-subheading"><div><h2>Справочники и нормативы</h2><p>Общие для четырёх смен Главного карьера</p></div><button className="ghost" onClick={() => { if (!dirty || window.confirm("Вернуться к отчёту без сохранения настроек?")) onBack(); }}>К отчёту</button></div>
    <fieldset disabled={pending}><section className="sp-settings-section"><h3>Экскаваторы</h3><p>Задайте номер, тип и направление. Для авто выберите основной самосвал.</p><div className="sp-table-scroll"><table className="sp-settings-table"><thead><tr><th>Номер</th><th>Тип</th><th>Направление</th><th>Самосвал по умолчанию</th><th>В списке</th></tr></thead><tbody>{settings.excavators.map((e, i) => <tr key={e.id} className={!e.active ? "sp-archived" : ""}><td><input aria-label={`Номер экскаватора ${i + 1}`} value={e.number} maxLength={30} onChange={event => change({ ...settings, excavators: settings.excavators.map((r, n) => n === i ? { ...r, number: event.target.value } : r) })} /></td><td><select aria-label={`Тип экскаватора ${i + 1}`} value={e.type} onChange={event => change({ ...settings, excavators: settings.excavators.map((r, n) => n === i ? { ...r, type: event.target.value } : r) })}>{excavatorTypes.map(t => <option key={t}>{t}</option>)}</select></td><td><select aria-label={`Направление экскаватора ${i + 1}`} value={e.direction} onChange={event => change({ ...settings, excavators: settings.excavators.map((r, n) => n === i ? { ...r, direction: event.target.value as "rail" | "truck" } : r) })}><option value="rail">ЖД</option><option value="truck">Авто</option></select></td><td><select aria-label={`Самосвал экскаватора ${i + 1}`} disabled={e.direction === "rail"} value={e.truck} onChange={event => change({ ...settings, excavators: settings.excavators.map((r, n) => n === i ? { ...r, truck: Number(event.target.value) } : r) })}>{truckTypes.map(t => <option key={t} value={t}>БЕЛАЗ {t} т</option>)}</select></td><td><button className="ghost" onClick={() => change({ ...settings, excavators: settings.excavators.map((r, n) => n === i ? { ...r, active: !r.active } : r) })}>{e.active ? "В архив" : "Вернуть"}</button>{issues.find(x => x.path === `excavators.${i}`) && <small className="sp-error">{issues.find(x => x.path === `excavators.${i}`)?.message}</small>}</td></tr>)}</tbody></table></div>
      {!settings.excavators.length && <p className="sp-muted">Добавьте первый экскаватор. Номера и нормативы заполняются по вашим данным.</p>}
      <button className="ghost" onClick={() => change({ ...settings, excavators: [...settings.excavators, { id: crypto.randomUUID(), number: "", type: "ЭКГ-10", direction: "rail", truck: 130, active: true }] })}>Добавить экскаватор</button></section>
      <section className="sp-settings-section"><h3>Нормативы времени погрузки</h3><p>Пустое поле означает, что норматив ещё не задан.</p><div className="sp-table-scroll"><table className="sp-settings-table"><thead><tr><th>Тип экскаватора</th><th>Думпкар<small>Десятичные минуты</small></th>{truckTypes.map(t => <th key={t}>БЕЛАЗ {t} т<small>Минуты и секунды</small></th>)}</tr></thead><tbody>{excavatorTypes.map(type => <tr key={type}><th scope="row">{type}</th>{[null, ...truckTypes].map(truck => { const key = normKey(type, truck === null ? "rail" : "truck", truck); return <td key={key}><TimeFields label={`Норматив ${type}, ${truck === null ? "ЖД" : `${truck} т`}`} format={truck === null ? "decimalMinutes" : "ms"} value={settings.norms[key] ?? ["", ""]} error={issues.find(x => x.path === `norms.${key}`)?.message} onChange={parts => change({ ...settings, norms: { ...settings.norms, [key]: parts } })} /></td>; })}</tr>)}</tbody></table></div></section>
      <section className="sp-settings-section"><h3>Причины невыполнения</h3><div className="sp-reason-settings">{settings.reasons.map((r, i) => <div key={r.id}><input aria-label={`Причина ${i + 1}`} value={r.name} maxLength={150} onChange={e => change({ ...settings, reasons: settings.reasons.map((x, n) => n === i ? { ...x, name: e.target.value } : x) })} /><button className="ghost" onClick={() => change({ ...settings, reasons: settings.reasons.map((x, n) => n === i ? { ...x, active: !x.active } : x) })}>{r.active ? "В архив" : "Вернуть"}</button></div>)}</div><button className="ghost" onClick={() => change({ ...settings, reasons: [...settings.reasons, { id: crypto.randomUUID(), name: "", active: true }] })}>Добавить причину</button></section>
      <div className="sp-settings-save"><button className="primary" onClick={save}>{pending ? "Сохраняем…" : "Сохранить настройки"}</button>{dirty && <span>Есть несохранённые изменения</span>}</div></fieldset>
    {message && <p className={issues.length ? "sp-alert sp-error" : "sp-alert"} role="status">{message}</p>}
    <details className="sp-audit" onToggle={async e => { if (e.currentTarget.open) { const result = await settingsAudit(); if (result.ok) setAudit(result.value); } }}><summary>История изменений справочников</summary>{audit.length ? <ul>{audit.map(a => <li key={a.id}>{new Date(a.at).toLocaleString("ru-RU", { timeZone: "Asia/Yekaterinburg" })} · {a.author}</li>)}</ul> : <p>Сохранённых изменений пока нет.</p>}</details>
  </section>;
}
